//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by RAYTRACE.RC
//
#define IDR_MAINFRAME                   2
#define IDD_ABOUTBOX                    100
#define ID_VIEW_MODEL                   32771
#define ID_VIEW_IMAGE                   32772
#define ID_FILE_RENDER                  32773
#define ID_FILE_STOP_RENDER             32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
